### ISSUE TITLE
http2 does not work

### ISSUE THREAD

**Issue by MoMannn** [JCMais/node-libcurl#231]
Setting `HTTP_VERSION` option to `CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE` still sends http1.1 request.

I tried with Curl:

`curl.setOpt('URL', 'http://localhost:3000');
  curl.setOpt('HTTP_VERSION', 'CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE');`

And with curly:

`const response = await curly.get('http://localhost:3000', {
     HTTP_VERSION: 'CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE'
  })`

**Comment by JCMais** [comment]
Hi.

This is not how you are supposed to set it, you must use one of the values from the `CurlHttpVersion` object:
```
const { Curl, CurlHttpVersion } = require('node-libcurl')

// ...

curl.setOpt('HTTP_VERSION', CurlHttpVersion.V2PriorKnowledge)
```

For the possible values see https://jcmais.github.io/node-libcurl/enums/_enum_curlhttpversion_.curlhttpversion.html

Sorry if this is not clear in the documentation.

**Comment by MoMannn** [comment]
Yeah documentation only points to: https://curl.haxx.se/libcurl/c/CURLOPT_HTTP_VERSION.html 

No prob, thanks for quick response, it works now :)

**Comment by JCMais** [comment]
I see, those names on libcurl documentation are C constants declared by libcurl, if you see them in other options they probably have a corresponding object in this library, if they don't or the option is not supported, or we have a missing option, which should be reported.

**Comment by MoMannn** [comment]
@JCMais I am guessing [piplining / multiplexing](https://curl.haxx.se/docs/http2.html) option is not yet supported?

**Comment by JCMais** [comment]
It's, but then you will need to handle your own `Multi` instance, as it's currently not possible to change options on the one used internally by `Curl` or the `curly` function (which internally uses `Curl`). For an example on how to use the `Multi` instance directly, see [`examples/04-multi.js`](https://github.com/JCMais/node-libcurl/blob/02f813b9a7928b4c72916fc917cdc258a46e2e19/examples/04-multi.js)

You should be able to enable PIPELINING like this:
```
const { Easy, Multi, CurlPipe } = require('node-libcurl')

// ...

// https://jcmais.github.io/node-libcurl/enums/_enum_curlpipe_.curlpipe.html
multi.setOpt('PIPELINING', CurlPipe.Multiplex)
```
Keep in mind that HTTP/1 pipelining was removed from libcurl 7.62, and since then `MULTIPLEX` is enabled by default. The other options do nothing starting with that version.

The current prebuilt binary is built with libcurl 7.69.1.

**Comment by MoMannn** [comment]
Thanks. I need it for http2 so no problems here.

**Comment by MoMannn** [comment]
@JCMais Do you maybe have a similar example for push (push_promise) like you do for multi?

**Comment by JCMais** [comment]
`CURLMOPT_PUSHFUNCTION` is currently not supported by the binding, so it's not possible to accept push_promise frames currently. If you think this would be a great feature to have please create a new issue with the feature request and I should be able to take a look into it next week (or if you can, pull requests implementing it are also welcome)
