### ISSUE TITLE
OPENSOCKETFUNCTION typescript bindings

### ISSUE THREAD

**Issue by tharun208** [JCMais/node-libcurl#268]
Hi, I am trying `node-libcurl` to connect to create a WebSocket client and perform transforming messages, as referenced from this example(https://phpandmore.net/2015/02/17/implementing-web-sockets-with-curl/).

I am trying to set this option `OPENSOCKETFUNCTION`, but it is not available.

and also some help with this creating client will be helpful

**Comment by JCMais** [comment]
`OPENSOCKETFUNCTION` is not available. Mostly because it would be hard to create bindings for this function, as it relies on working with the raw socket.

However, it's possible to create a WebSockets client using this library by using [`Easy.onSocketEvent`](https://node-libcurl-docs.netlify.app/classes/_lib_easy_.easy.html#onsocketevent)

See a working example here: https://github.com/JCMais/node-libcurl/blob/develop/examples/21-websockets-client.js

**Comment by JCMais** [comment]
Closing this, feel free to re-open if you have issues.

**Comment by henullcom** [comment]
Hi @JCMais ,
i was also looking for this functionality because i had a problem with the websocket example.
example at: https://github.com/JCMais/node-libcurl/blob/develop/examples/21-websockets-client.js
Everything is fine with my http://localhost:8080.
But when I connect to any websocket server using https.
I cannot read the returned data content.
Response:
[
'\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00�\x00\x04\x00\x01\x00\x00\x00\x05\x00�� �\x00\x00\x04\b\x00\x00\x00\x00\x00\x7F�\x00'
]
I have searched everything on the internet about this but to no avail. Please help.
Thank you.

**Comment by JCMais** [comment]
@henullcom unfortunately the state of this is the same as before, `OPENSOCKETFUNCTION` is not supported. The example is just a starting point, I did not test it with binary data, so the binary frame parsing is probably wrong.

**Comment by henullcom** [comment]
Hi @JCMais ,
Can you try to test and write an example of websocket connecting to https using ssl?.
This is very useful to use with real servers.
I have followed your [21-websockets-client.js](https://github.com/JCMais/node-libcurl/blob/develop/examples/21-websockets-client.js) example but am unable to read the Response Headers returned when connecting to any https(wss) socket server.
Here is the server and I use it to test:
wss://demo.piesocket.com/v3/channel_123?api_key=VCXCEuvhGcBDP7XhiJJUDvR1e1D3eiVjgZ9VRiaV&notify_self
(https://www.piesocket.com/websocket-tester)
Thank you very much for this.
