### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by anthonykozak** [JCMais/node-libcurl#28]
Hi,
I just installed the latest nodejs, and libcurl, and had this error :

"5869 error Windows_NT 6.1.7601
5870 error argv "D:\programmes\nodejs\\node.exe" "D:\programmes\nodejs\node_modules\npm\bin\npm-cli.js" "install" "node-libcurl"
5871 error node v0.12.7
5872 error npm v2.11.3
5873 error code ELIFECYCLE
5874 error node-libcurl@0.5.1 install: node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild
5874 error Exit status 1
5875 error Failed at the node-libcurl@0.5.1 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && pangyp rebuild'.
5875 error This is most likely a problem with the node-libcurl package,
5875 error not with npm itself."

The complete log is here http://jpst.it/Ba8O.
Thank you for your help !
Best regards,
Anthony

**Comment by JCMais** [comment]
do you have python and git installed?

**Comment by anthonykozak** [comment]
yes 
Python 2.7.10
git version 1.9.5.github.0
and visual studio 2013

**Comment by anthonykozak** [comment]
here is the console log attached.
![log](https://cloud.githubusercontent.com/assets/973985/9430522/72dce03c-49f9-11e5-98aa-cc92def13d78.jpg)

is there any other way to install node-libcurl ? like downloading a precompiled version and putting it in a specific path ?

**Comment by JCMais** [comment]
> is there any other way to install node-libcurl ? like downloading a precompiled version and putting it in a specific path ?

Currently, there isn't.


I don't know exactly what is this problem that you are having, never saw it, but from what I could read, it's probably because you have a incorrect installation of Visual Studio.

Can you try reinstalling it? If possible try a more recent version, like [Visual Studio 15](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx)

**Comment by anthonykozak** [comment]
ok I installed Visual Studio 2015 with C#, and C++ modules and it finally worked.

I guess the module can't work on linux, as it needs visual studio ?..

**Comment by JCMais** [comment]
Visual Studio is a Windows only dependency, since its the most supported C++ compiler for that platform.
You don't need Visual Studio on Linux, your linux distribution should already have a C++ compiler called gcc. Just make sure it's at the version 4.8 or above.

Also, pasting is not going to work, since it was compiled on a different os/architecture.
