### ISSUE TITLE
Breaking change in v2.3.4

### ISSUE THREAD

**Issue by ddolcimascolo** [JCMais/node-libcurl#329]
Hi @JCMais 

With v2.3.4 I now have this error message at runtime

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/share/stordata/collectors/node_modules/node-libcurl/lib/binding/node_libcurl.node)
```

It reminds me of https://github.com/JCMais/node-libcurl/issues/278 but this time build and packaging works fine. For the record, we package and run on Debian Stretch (9).

Do you know what might be wrong?

Thanks,
David

**Comment by JCMais** [comment]
Hi @ddolcimascolo, GitHub has removed support for Ubuntu 16, which was the version used previously to build the prebuilt binaries. 

I had to upgrade otherwise there would be no need to have the prebuilt binaries on *nix, but I forgot about this GLIBC issue.

Do you know if it is possible to support older glibc versions when building with Ubuntu 18?


Does building from source work?

**Comment by ddolcimascolo** [comment]
I'll try to build from source and keep you posted.

**Comment by ddolcimascolo** [comment]
And for the record about the build, that's what we do to support Debian 9 (until middle of this year when it'll go EOL): build the Debian package in a container built after `debian:stretch`

**Comment by JCMais** [comment]
@ddolcimascolo could you check if the prebuilt binaries are working for you now?  I tested using docker and it seems to be working.

This should not happen again in the future as I will be using a container to build the Linux binaries moving forward.

**Comment by ddolcimascolo** [comment]
Hi @JCMais

It's OK now. Thx for fixing!

Cheers,
David
