### ISSUE TITLE
Installation on WSL (Ubuntu) crashing windows with BSOD

### ISSUE THREAD

**Issue by a-tonchev** [JCMais/node-libcurl#336]
Trying to upgrade/install to latest node-libcurl (from 2.3.3 to 2.3.4) is causing Windows to crash, mixing up package.json and yarn.lock

BSOD: KERNEL_SYSTEM_CHECK_FAILURE

In a large project, this is the only library that can not be installed and crash on every try. At first I was thinking that my windows is broken, so I reinstalled it, but the same problem happens. 

https://github.com/microsoft/WSL/issues/4537#issuecomment-1034760068

Win 11
WSL 1 with Ubuntu 20.04

**Comment by JCMais** [comment]
Hi, I develop the addon using WSL 2 on Windows 10, and I am not able to reproduce it. I would recommend upgrading to WSL 2 if possible.

With that said, I do not think this is an issue with the addon, it is an issue with WSL and probably the way it handles multiple file descriptors bein opened at the same time. 

WSL 2 has a different filesystem handling, so that is probably why I do not see this issue.

**Comment by a-tonchev** [comment]
@JCMais out of curiosity - how did you solve the problem with hot reloading on WSL2? My biggest issue with WSL2 is the hot reloading, I want to use my Windows IDE (Webstorm) for edit files and git commands but to have the code running in linux.
Moving files into the linux filesystem makes somehow the IDE slow and git does not work well.

**Comment by JCMais** [comment]
@a-tonchev I use VSCode with WSL2 and I have no issues with the filesystem, it is as fast as opening a file in the Windows filesystem. With WSL2 access to the Windows filesystem from within WSL2 is slower than it was with WSL1, but the WSL2 own filesystem has performance close to native.

In your case, my assumption would be that the IDE is not optimized for development using WSL.
