### ISSUE TITLE
curl.enable with Easy

### ISSUE THREAD

**Issue by KokeroO** [JCMais/node-libcurl#356]
I need to use curl.enable(CurlFeature.NoDataParsing) or curl.enable.(CurlFeature.Raw) with Easy and Multi.

I've tried everything for 2 days and I can't find a solution.

**Comment by JCMais** [comment]
The `Easy` and `Multi` classes are basically a 1:1 conversion of the C libcurl API, thus they do not provide this helper.

This should not be needed for the native Easy and Multi instances, because they don't parse the data. The data is provided as-is the same way libcurl provides them in the [CURLOPT_WRITEFUNCTION](https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html).

What are you trying to accomplish?

If you want a behavior similar to what is done in the `Curl` class, take a look at the default write function that is used:

https://github.com/JCMais/node-libcurl/blob/96201eba595042fa0838e81b381caa2fa6384184/lib/Curl.ts#L963-L977

And then in the `onEnd` function that is called when the `Multi` instance marks the easy handle as finished:

https://github.com/JCMais/node-libcurl/blob/96201eba595042fa0838e81b381caa2fa6384184/lib/Curl.ts#L102

https://github.com/JCMais/node-libcurl/blob/96201eba595042fa0838e81b381caa2fa6384184/lib/Curl.ts#L323-L382
