### ISSUE TITLE
Sockets kept open after calling .close()

### ISSUE THREAD

**Issue by tomrf** [JCMais/node-libcurl#78]
I'm using node-libcurl to run through a large set of URLs.  For each URL I create a Curl instance, perform() the curl and then close() the instance.

The problem I'm facing is that sockets are kept open in state ESTABLISHED, until they time out and hang around forever in state CLOSE_WAIT.  After 1024 curls my process is out of allowed sockets, and all further curls fail.

Any idea what could be causing this?

**Comment by JCMais** [comment]
Post some code that can reproduce the issue.

Also, Node.js and libcurl version. You can get the libcurl version that was used to build the addon with ``Curl.getVersion()``.

**Comment by tomrf** [comment]
Node version: v6.9.1

libcurl version: libcurl/7.29.0 NSS/3.21 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3

Code:

```
var Curl = require( 'node-libcurl' ).Curl;

function curlUrl(url, callback) {
	var curl = new Curl();
	curl.setOpt('URL', url);
	curl.setOpt('FOLLOWLOCATION', true);
	curl.on('end', function(statusCode, body, headers) {
		var results = {
			http_code: 	 statusCode,
			total_time:  this.getInfo('TOTAL_TIME'),
		}
	    curl.close();
	    callback(results);
	});
	curl.on('error', function (err, code) {
		curl.close.bind(curl);
		callback(null, code);
	});
	curl.perform();
}

for (var i = 0; i < 10; i++) {
	curlUrl('example.com', function(results, errorCode) {
		console.log(results, errorCode);
	});;
}

setInterval(function() { }, 1000);
```

This example will keep ten sockets open in ESTABLISHED state until the server closes the connection, at which point the sockets will hang around in CLOSE_WAIT state til the node process is terminated.

**Comment by JCMais** [comment]
This is not something I can "fix" at this side, because there is nothing to fix.

You are having this problem because of the connection cache libcurl uses internally, some links that are worth to read about the issue:

https://sourceforge.net/p/curl/bugs/550/
https://sourceforge.net/p/curl/bugs/1010/
https://curl.haxx.se/mail/lib-2011-09/0184.html (use "Next in thread" at the footer to follow the discussion)

And some options that you probably should take a look:
https://curl.haxx.se/libcurl/c/CURLMOPT_MAXCONNECTS.html
https://curl.haxx.se/libcurl/c/CURLMOPT_MAX_HOST_CONNECTIONS.html
https://curl.haxx.se/libcurl/c/CURLOPT_MAXCONNECTS.html
https://curl.haxx.se/libcurl/c/CURLOPT_FRESH_CONNECT.html
https://curl.haxx.se/libcurl/c/CURLOPT_FORBID_REUSE.html

Also, you are using the ``Curl`` wrapper, keep in mind that this one doesn't exposes the internal ``Multi`` handle it uses, so if you need to set any option there, you need to create one yourself.

**Comment by tomrf** [comment]
Thanks for the pointers!

I upgraded node to 6.9.4, and I am no longer seeing this issue -- even without setting MAXCONNECTS etc.

Pretty sure I haven't done and changes to the code.

Oh well -- all good for my case at least.  Closing the issue.
