### ISSUE TITLE
Using NTLM causes half the requests to fail

### ISSUE THREAD

**Issue by kevinhikaruevans** [JCMais/node-libcurl#9]
I'm working on a little project and I'm trying to authenticate with NTLM. 

This is what I'm using to make the request:

```
var Promise = require('bluebird');
var express = require('express');
var Curl = require( 'node-libcurl' ).Curl;

function createAPIRequest(url) {
  return new Promise(function(resolve, reject) {
    var curl = new Curl();
    curl.setOpt('URL', 'http://chum:8048/Sandbox/OData/' + url);
    curl.setOpt('HTTPAUTH', Curl.auth.NTLM);
    curl.setOpt('USERPWD', ''); //stuff goes in here
    curl.setOpt('HTTPHEADER', ['Content-Type: application/json', 'Accept: application/json']);

    curl
      .on('end', function(code, body, headers) {
        console.log(code);
        console.log(headers);

        resolve(JSON.parse(body || '{}'));
        this.close();
      })
      .on('error', function(e) {
        reject(e);
        this.close();
      })
      .perform();
  });
}
```

The thing is, it alternates between working and not working. Not sure if there's like some cache that needs to be cleared between requests and it's not or something. Like, it'll work and the server will return a 200, then the next request, it'll be a 401, then it'll go back to 200 and keep repeating.

The server is Microsoft Dynamics NAV 2013 R2. This only occurs in Linux using libcurl 7.40.0 or 7.32.0, but works fine under Windows using libcurl 7.40.0.

**Comment by JCMais** [comment]
Can you post the output of ``curl -v -V``?

And if possible, the output of running the above command, but with the verbose flag (showing both correct and wrong requests).

**Comment by kevinhikaruevans** [comment]
Here you go:

```
curl 7.32.0 (x86_64-pc-linux-gnu) libcurl/7.32.0 OpenSSL/1.0.1e zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

**Comment by JCMais** [comment]
Can you enable set FORBID_REUSE to true and check if the issue persists?


``curl.setOpt( 'FORBID_REUSE', true );``

**Comment by kevinhikaruevans** [comment]
Hmm, that doesn't seem to work at all with that.

With that enabled, I end up getting this error: `Unhandled rejection Error: Couldn't connect to server`

**Comment by JCMais** [comment]
Try using libcurl >= 7.38, a bug was fixed in this version about the error you received.

>>  NTLM: ignore CURLOPT_FORBID_REUSE during NTLM HTTP auth

**Comment by sridharspeaks** [comment]
Hi,

I am also getting a similar error and seriously got strucked here. 

npm WARN package.json express-json@1.0.0 No repository field.
npm WARN engine node-libcurl@0.1.3: wanted: {"node":">= 0.8.0 && < 0.11.0"} (current: {"node":"0.10.36","npm":"1.4.28"})

> node-libcurl@0.1.3 install /usr/local/node/ayla/node_modules/node-libcurl
> node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild

Cannot find curl's header file.

npm ERR! node-libcurl@0.1.3 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.1.3 install script.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.17.1.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "node-libcurl"
npm ERR! cwd /usr/local/node/ayla
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Just wanted to check if there is any solution available. Also may be due to this erorr, I am unable to do npm install node-curl.

**Comment by JCMais** [comment]
@sridharspeaks your issue is not related to this one, create a new issue, and post the output of running npm install with the flag --loglevel set to verbose. ``npm install --loglevel verbose``

**Comment by sridharspeaks** [comment]
I have placed it as a separate request. Here is the link for below. 
https://github.com/JCMais/node-libcurl/issues/10

Thanks for looking into the issue.

**Comment by JCMais** [comment]
Timing out.
